# Generated by Django 5.0.6 on 2024-07-03 00:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('DVELEOPER', 'DVELEOPER'), ('PROJECT_ADMIN', 'PROJECT_ADMIN'), ('USER', 'USER')], max_length=40)),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_Number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. 10 digits allowed.", regex='^\\+?1?\\d{10}$')])),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('avtar', models.FileField(blank=True, null=True, upload_to='Profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
